app:    
     - area_shape_basico: 
          info: 'Limites São Luís'
          tabela: limites_sao_luis
          tipo: poligono
     - area_shape_basico: 
          info: 'Anél Viário'
          tabela: anel_viario
          tipo: poligono
     - camada_padrao:
          tipo: ponto
          info: 'Informações de lotes'
          tabela: lotes_por_ponto
          campos: finais_prior#finais_divida#finais_estado_de_
          descricao: 'Prioridade#Divida#Estado de Conservação'
          popup: finais_de_uso#finais_prior#finais_divida#finais_estado_de_
          desc_popup: 'Uso#Prioridade#Divida#Estado de Conservação'
     - camada_padrao:
          tipo: ponto
          info: 'Equipamentos Público'
          tabela: equipamento_publico
          campos: educacao#saude#seguranca#cultural#assistencia_social
          descricao: 'Educação#Saúde#Segurança#Cultural#Assistência Social'
          popup: tipo#name
          desc_popup: 'Tipo#Nome'
     - camada_padrao:
          tipo: poligono
          info: 'Tombamento'
          tabela: tombamento
          campos: name
          descricao: 'Nome'
          popup: name
          desc_popup: 'Nome'  
     - topico: 
          titulo: 'População na Área de Análise'          
          descricao: 'Este tópico apresenta informações da população na área de interesse do Vem Pro Centro. Utilize os controles abaixo para mudar a visualização do mapa para a maneira desejada.'
          mapa1:
               titulo: '**Distribuição de Mulheres por Setor censitario**'
               tabela: pdc_bid_ibge
               camada: setor_censitario                
               variavel: 'mulheres_14_anos_ou_mais#mulheres_resp_pelo_dom#idosos_65_anos_ou_mais#crianca_13_ou_menos'
               alias: 'Mulheres (14 anos ou mais):#Mulheres responsáveis por Domicílios#Idosos#Crianças'  
               descricao: 'Verificamos que as mulheres são a maioria da população na área de interesse e têm um papel fundamental na responsabilidade dos lares'                       
               camada_extra: 'lotes_por_ponto' 
               camada_interna: tombamento   
               camada_base: anel_viario                     
          grafico1:
               titulo: '**Distribuição da população**'
               tabela: pdc_bid_ibge
               x:
                    - mulheres_14_anos_ou_mais
                    - mulher_responsavel
                    - idosos_65_anos_ou_mais
                    - crianca_13_ou_menos
               x_alias:
                    - Mulheres de 14 anos ou mais
                    - Mulher Responsável
                    - Idosos de 65 anos ou mais
                    - Crianças de 13 anos ou menos
               y:
                    - Quantidade
               tipo: barra_vertical
               descricao: 'Distribuição da poplação na categorias'                                                                   
     - topico:  
          titulo: 'Habitações Precárias'          
          descricao: 'Analisaremos algumas informações dos domicílios.'          
          mapa1:
               titulo: '**Distribruição de banheiros nas habitações**'
               tabela: pdc_bid_ibge
               camada: setor_censitario                
               variavel: 'dom_sem_banheiro_nem_sanitario#dom_sem_banheiro#dom_com_1_banheiro#dom_com_2_banheiro#dom_com_3_banheiro'
               alias: 'Dom. sem banheiro nem sanitário#Dom. sem banheiro#Dom. com até 1 banheiro#Dom. com até 2 banheiros#Dom. com até 3 banheiros'  
               descricao: 'Distribuição de banheiros nos domicílios da área de interesse. Ao clicar, observamos outros fatores relacionados.'     
               camada_extra: 'equipamento_publico'
               camada_interna: ''    
               camada_base: 'anel_viario'                    
          grafico1:
               titulo: '**Distribuição da população**'
               tabela: pdc_bid_ibge
               x:
                    - mulheres_14_anos_ou_mais
                    - mulher_responsavel
                    - idosos_65_anos_ou_mais
                    - crianca_13_ou_menos
               x_alias:
                    - Mulheres de 14 anos ou mais
                    - Mulher Responsável
                    - Idosos de 65 anos ou mais
                    - Crianças de 13 anos ou menos
               y:
                    - Quantidade
               tipo: barra_vertical
               descricao: 'Distribuição da poplação por setor censitário'                                                                            
          grafico2:
               titulo: '**Distribuição de Esgoto**'
               tabela: pdc_bid_ibge
               x:
                    - dom_banh_excl_rede_geral
                    - dom_banh_excl_fossa_septica
                    - dom_banh_excl_fossa_rud
                    - dom_banh_excl_vala
                    - dom_banh_excl_rio_lago_mar
                    - dom_banh_excl_outro
               x_alias:
                    - Rede Geral
                    - Fossa Séptica
                    - Fossa Rudimentar
                    - Vala
                    - Rio, Lago ou Mar
                    - Outro
               y:
                    - Quantidade
               tipo: pizza
               descricao: 'Distribuição de acesso a esgotamento'
          grafico3:
               titulo: '**Distribuição de banheiros**'
               tabela: pdc_bid_ibge
               x:
                    - dom_sem_banheiro_nem_sanitario
                    - dom_com_1_banheiro
                    - dom_com_2_banheiro
                    - dom_com_3_banheiro
               x_alias:
                    - Dom. sem banheiro nem sanitário
                    - Dom. com 1 banheiro
                    - Dom. com 2 banheiros
                    - Dom. com 3 banheiros
               y:
                    - Quantidade
               tipo: barra_vertical
               descricao: 'Distribuição de acesso a banheiros nos lares'
          grafico4:
               titulo: '**Distribuição de Água**'
               tabela: pdc_bid_ibge
               x:
                    - dom_abastecimento_agua_rede_geral
                    - dom_abastecimento_agua_poco_nascente
                    - dom_abastecimento_agua_chuva_cisterna
                    - dom_abastecimento_agua_outra
               x_alias:
                    - Rede Geral
                    - Poço ou Nascente
                    - Chuva ou Cisterna
                    - Outro
               y:
                    - Quantidade
               tipo: barra_horizontal
               descricao: 'Forma de fornececimento de água nos domicílios'
          grafico5:
               titulo: '**Distribuição de Lixo**'
               tabela: pdc_bid_ibge
               x:
                    - dom_part_lixo_coletado_servico
                    - dom_part_lixo_coletado_cacamba_servico
                    - dom_part_lixo_queimado_propriedade
                    - dom_part_lixo_enterrado_propriedade
                    - dom_part_lixo_terreno_baldio
                    - dom_part_lixo_rio_lago_mar
                    - dom_part_lixo_outro
               x_alias:
                    - Serviço de Coleta
                    - Caçamba 
                    - Lixo Queimado
                    - Enterrado na Propriedade
                    - Terreno Baldio
                    - Rio, Lago ou Mar
                    - Outro
               y:   
                    - Quantidade
               tipo: pizza
               descricao: 'Forma de coleta de lixo nos domicílios.'
     - topico: 
          titulo: 'Lotes'          
          descricao: 'Informação dos lotes na área de interesse'        
          mapa1:
               titulo: '**Lotes**'
               tabela: pdc_bid_lotes
               camada: lotes                
               variavel: 'tipologia_finais#conservacao_finais#uso_finais#prioridade_finais#divida'
               alias: 'Tipologia#Estado de Conservação#Uso#Prioridade#Divida'  
               descricao: 'Visualização de informações dos lotes da área de análise.'
               camada_extra: 'equipamento_publico'   
               camada_interna: '' 
               camada_base: 'anel_viario'  
     